WAZO-2172: call record start
wazo-platform/wazo-calld pull request #142
Opened 2021-01-14 19:44 UTC by bloom1

2021-01-14 19:55 UTC, bloom1 commented
recheck

2021-01-15 14:26 UTC, fblackburn1 requested changes
Can you split test_calls to test_call_records file? This file is definitively too long

2021-01-15 14:26 UTC, fblackburn1 commented on CHANGELOG.md
> +  * `recorded`
```suggestion
  * `record_state`
```

2021-01-15 14:26 UTC, fblackburn1 commented on wazo_calld/plugin_helpers/ami.py
> +
Why we cannot use ari to get variable like other endpoints?

2021-01-15 14:48 UTC, fblackburn1 requested changes
Triggering multiple start will start simultaneous MixMonitor and you will need to trigger the same amount of stop to really stop de recording
We should verify that call is not currently recorded before sending another MixMonitor command

2021-01-15 19:35 UTC, fblackburn1 approved these changes

2021-01-18 13:05 UTC, fblackburn1 approved these changes

2021-01-18 13:07 UTC, fblackburn1 commented
@bloom1 FYI I have no objection if you set `auto-merge` label after quick fix that dismissed my approval :)

2021-01-18 13:11 UTC, bloom1 commented
> @bloom1 FYI I have no objection if you set `auto-merge` label after quick fix that dismissed my approval slightly_smiling_face

Hehe alright :smile:

2021-01-18 14:26 UTC, merged