Pull request for WAZO-3690-transfer-race-condition
wazo-platform/wazo-calld pull request #310
Opened 2024-03-29 14:23 UTC by sduthil

## transfers: split transfer object creation from transfer initiation

Why:

* Scenario:
  * transfer is initiated
  * channels are moved to stasis by the API thread
  * channels both enter stasis into the bus thread
  * the transfer object is not created yet in the API thread, preventing
    the transfer to start
  * the transfer is created too late by the API thread

## transfers: rename non-stasis states

Why:

* clarify the state we're in

## transfers: move event code to the service

Why:

* remove duplication

## tests: allow for some time for transfer deletion

## fixup! transfers: move event code to the service

## transfers: move creation logic to service

Why:

* avoid duplication between TransferStateReady and
  TransferStateNonStasis

2024-04-01 13:26 UTC, pc-m requested changes
Good job. There's a fixup commit left in the history. I'm pretty sure you meant to rebase/fixup that commit.

2024-04-03 08:56 UTC, sduthil commented
Tests failure were due to an unrelated flaky test. The flakiness should be fixed in this other PR (auto-merge): https://github.com/wazo-platform/wazo-calld/pull/311

2024-04-03 09:59 UTC, sduthil commented
recheck

2024-04-03 13:06 UTC, pc-m approved these changes

2024-04-03 13:43 UTC, merged